# .ps_project/config.yaml:

version: 1

project: "project-handle"
experiment: "javihuertas/faceswap" #[optional, default:<repo name>]
type: "single" #[single|multi-grpc|multi-mpi]
ports: "5000" #[optional, default:5000]

paths: #[optional]
  workdir: "/home/playgroung"
  artifacts: "/artifacts"
model: #[optional, but required for model parsing and model deployments]
  type: "Tensorflow" #[required for model, one of: Tensorflow|ONNX|Custom]
  path: "/storage/models"

worker:
  container: "tensorflow/tensorflow:1.8.0-gpu"
  command: "nvidia-smi"
  machine-type: "K80"
  count: 1 #[required for multi-node]
parameter-server: #[required for multi-node]
  container: "tensorflow/tensorflow:1.8.0-gpu"
  command: "nvidia-smi"
  machine-type: "K80"
  count: 1
filters:
  branches:
    ignore: irrelevant-branch
  tags:
    only:
      - v.*
      - latest

checks: #[optional]
  defaults:
    precision: 3
    round: up
    only-prs: true
  tensorflow:accuracy:
    target: 0.7..
    aggregation: mean
  tensorflow:loss:
    target: ..0.025
    aggregation: max
